import type { Metadata } from "next";
import "./globals.css";
import { helveticaNeue, loRes9Wide, loRes21Serif } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`antialiased ${helveticaNeue.variable} ${loRes9Wide.variable} ${loRes21Serif.variable}`}>
        {children}
      </body>
    </html>
  );
}
